export const types = [
  { name: 'Account Management' },
  { name: 'Account Management : QBR' },
  { name: 'Account Management : QBR Prep' },
  { name: 'Account Management : Data Request' },
  { name: 'Account Management : Renewal' },
  { name: 'Account Management : Upsell' },
  { name: 'Account Management : Cross-sell' },
  { name: 'Account Management : Support' },
  { name: 'Account Management : Legal' },
  { name: 'Account Management : Commercials' },
  { name: 'Account Management : Contraction' },
  { name: 'Account Management : Debooking' },
  { name: 'Account Management : Pre-Sales' },
  { name: 'Account Management : Status Update' },
  { name: 'Documents' },
  { name: 'Documents - Documentation' },
  { name: 'Documents - Technical' },
  { name: 'Documents - Marketing' },
  { name: 'Documents - Security' },
  { name: 'Implementation - QA' },
  { name: 'Go live' },
  { name: 'Legal' },
  { name: 'Legal - SLA' },
  { name: 'Legal - Process' },
  { name: 'Legal - Sales Order' },
  { name: 'Legal - T&Cs' },
  { name: 'Legal - Data Protecttion' },
  { name: 'Onboarding - Account assignment' },
  { name: 'Onboarding - Kick off call' },
  { name: 'Onboarding - Implementation' },
  { name: 'Onboarding - client sign off' },
  { name: 'Plan' },
  { name: 'Plan - DR' },
  { name: 'Plan - BC' },
  { name: 'Policies' },
  { name: 'Policies - DEI' },
  { name: 'Policies - AntiBribery' },
  { name: 'Policies - Green' },
  { name: 'Process' },
  { name: 'Process - Internal' },
  { name: 'Process - External' },
  { name: 'Process - Technical' },
  { name: 'Security' },
  { name: 'Security - Review' },
  { name: 'Sales' },
  { name: 'Sales - Business Case' },
  { name: 'Sales - Collaterals' },
  { name: 'Sales - Commercials' },
  { name: 'Sales - Demo' },
  { name: 'Sales - Executive Summary' },
  { name: 'Sales - Quote' },
  { name: 'Sales - Workshop' },
  { name: 'Sponsors' },
  { name: 'Sponsors - Meet' },
  { name: 'Sponsors - Approval' },
  { name: 'Sponsors -  References' },
  { name: 'Strictly After' },
  { name: 'Others' },
];

export const category = [
  { name: 'Documents' },
  { name: 'Legal' },
  { name: 'Sponsors' },
  { name: 'Plans' },
  { name: 'Policies' },
  { name: 'Process' },
  { name: 'Security' },
  { name: 'Others' },
];
